version: "3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
  app:
    build: .
    ports:
      - "3000:3000"
    restart: always
    environment:
      - APP_PORT=3000
      - ELASTICSEARCH_PORT=9200
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_INDEX=builder-tutorial
      - ELASTICSEARCH_TYPE=cars_list
    links:
      - elasticsearch
